language: node_js
node_js:
  - "4"
before_deploy:
  - openssl aes-256-cbc -K $encrypted_4f1a8e99c22c_key -iv $encrypted_4f1a8e99c22c_iv -in deploy_key.enc -out deploy_key -d
  - npm run build
deploy:
  - npm run deploy
branches:
  only:
    - master
