language: node_js
node_js:
  - "4"
install:
  - npm install
before_deploy:
  - npm run build
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
env:
  global:
    ENCRYPTION_LABEL: "4f1a8e99c22c"
    COMMIT_AUTHOR_EMAIL: "nils@schoenwald.media"
